import { Header } from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import "./styles/globals.css";
import Head from "next/head";
import { useLocale } from "next-intl";

export function generateStaticParams() {
  return [{ locale: "en" }, { locale: "ru" }, { locale: "am" }];
}

export const metadata = {
  title: "Genius Digital Trading",
  icons: {
    icon: "../favicon.ico",
  },
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }) {
  const locale = useLocale();

  // Show a 404 error if the user requests an unknown locale
  if (params.locale !== locale) {
    notFound();
  }

  return (
    <html lang={locale}>
      <Head>
        <title>Genius Digital Trading</title>
      </Head>
      <body>
        <Header locale={locale} />
        {children}
        <Footer />
      </body>
    </html>
  );
}
